services:
  frontend-pdv:
    build: .
    container_name: frontend-pdv
    ports:
      - "3001:3000"
    env_file:
      - .env
    networks:
      - pdv-network

networks:
  pdv-network:
    name: pdv-network
    external: true
